export const environment = {
  production: true,
  urlRaiz: 'https://apimur.amorinomoda.com',
  apiUrl: 'https://apimur.amorinomoda.com/api/test_api_crud',
  apiUrl2: 'https://apimur.amorinomoda.com/api/test_api',
  apiUrl3: 'https://apimur.amorinomoda.com/api/file',
  apiUrlTrabajador: 'https://apimur.amorinomoda.com/api/trabajador',
  apiUrlRegister: 'https://apimur.amorinomoda.com/api/register',
  apiUrlLogin: 'https://apimur.amorinomoda.com/api/login',
  apiUrlEmail: 'https://apimur.amorinomoda.com/api/enviar_correo',
  apiUrlEmpleador: 'https://apimur.amorinomoda.com/api/empleador',
  apiUrlUltimoEmpleador: 'https://apimur.amorinomoda.com/api/ultimo_empleador',
  apiUrlActividadUltimoEmpleador:
    'https://apimur.amorinomoda.com/api/actividad_ultimo_empleador',
  apiUpdateFile: 'https://apimur.amorinomoda.com/api/update/upload',
  apiListarFiles: 'https://apimur.amorinomoda.com/api/listar/files',
  apiDeleteFile: 'https://apimur.amorinomoda.com/api/update/upload',
  apiUrl3Carousel: 'https://apimur.amorinomoda.com/api/carousel/upload',
  apiUpdateFileCarousel:
    'https://apimur.amorinomoda.com/api/carousel/update/upload',
  apiListarFilesCarousel:
    'https://apimur.amorinomoda.com/api/carousel/listar/files',
  apiDeleteFileCarousel:
    'https://apimur.amorinomoda.com/api/carousel/update/upload',
  apiListarFilesTestimonio: 'https://apimur.amorinomoda.com/api/testimonios',
  apiListarFilesProducto: 'https://apimur.amorinomoda.com/api/productos',
  apiListarCursosProducto:
    'https://apimur.amorinomoda.com/api/productos/cursos',
  apiListarEspecialidadesProducto:
    'https://apimur.amorinomoda.com/api/productos/especialidades',
  apiListarDestacadosProducto:
    'https://apimur.amorinomoda.com/api/productos/destacados',
  apiUrl3Producto: 'https://apimur.amorinomoda.com/api/productos/subir',
  apiUpdateFileProducto: 'https://apimur.amorinomoda.com/api/productos/update',
  apiDeleteFileProducto: 'https://apimur.amorinomoda.com/api/productos',
  apiUrl3Banner: 'https://apimur.amorinomoda.com/api/banners/subir',
  apiUpdateFileBanner: 'https://apimur.amorinomoda.com/api/banners/update',
  apiListarFilesBanner: 'https://apimur.amorinomoda.com/api/banners',
  apiDeleteFileBanner: 'https://apimur.amorinomoda.com/api/banners',
  apiUrl3Slider: 'https://apimur.amorinomoda.com/api/sliders/subir',
  apiUpdateFileSlider: 'https://apimur.amorinomoda.com/api/sliders/update',
  apiListarFilesSlider: 'https://apimur.amorinomoda.com/api/sliders',
  apiDeleteFileSlider: 'https://apimur.amorinomoda.com/api/sliders',
};

/* export const environment = {
  production: true,
  urlRaiz: 'https://evv.pe',
  apiUrl: 'https://evv.pe/api/test_api_crud',
  apiUrl2: 'https://evv.pe/api/test_api',
  apiUrl3: 'https://evv.pe/api/file',
  apiUrlTrabajador: 'https://evv.pe/api/trabajador',
  apiUrlRegister: 'https://evv.pe/api/register',
  apiUrlLogin: 'https://evv.pe/api/login',
  apiUrlEmail: 'https://evv.pe/api/enviar_correo',
  apiUrlEmpleador: 'https://evv.pe/api/empleador',
  apiUrlUltimoEmpleador: 'https://evv.pe/api/ultimo_empleador',
  apiUrlActividadUltimoEmpleador:
    'https://evv.pe/api/actividad_ultimo_empleador',
  apiUpdateFile: 'https://evv.pe/api/update/upload',
  apiListarFiles: 'https://evv.pe/api/listar/files',
  apiDeleteFile: 'https://evv.pe/api/update/upload',
  apiUrl3Carousel: 'https://evv.pe/api/carousel/upload',
  apiUpdateFileCarousel: 'https://evv.pe/api/carousel/update/upload',
  apiListarFilesCarousel: 'https://evv.pe/api/carousel/listar/files',
  apiDeleteFileCarousel: 'https://evv.pe/api/carousel/update/upload',
  apiListarFilesTestimonio: 'https://evv.pe/api/testimonios',
  apiListarFilesProducto: 'https://evv.pe/api/productos',
  apiListarCursosProducto: 'https://evv.pe/api/productos/cursos',
  apiListarEspecialidadesProducto:
    'https://evv.pe/api/productos/especialidades',
  apiListarDestacadosProducto: 'https://evv.pe/api/productos/destacados',
  apiUrl3Producto: 'https://evv.pe/api/productos/subir',
  apiUpdateFileProducto: 'https://evv.pe/api/productos/update',
  apiDeleteFileProducto: 'https://evv.pe/api/productos',
  apiUrl3Banner: 'https://evv.pe/api/banners/subir',
  apiUpdateFileBanner: 'https://evv.pe/api/banners/update',
  apiListarFilesBanner: 'https://evv.pe/api/banners',
  apiDeleteFileBanner: 'https://evv.pe/api/banners',
  apiUrl3Slider: 'https://evv.pe/api/sliders/subir',
  apiUpdateFileSlider: 'https://evv.pe/api/sliders/update',
  apiListarFilesSlider: 'https://evv.pe/api/sliders',
  apiDeleteFileSlider: 'https://evv.pe/api/sliders',
  
};
 */
